// Bundles Preact + preact-render-to-string into self-contained ESM strings,
// emitted as `src/vendor/<name>.ts` files that export the code as a string.
//
// These vendored modules are injected into every dynamic-site module map so the
// agent-authored SSR code can `import { h } from "preact"` etc. without any
// network access (the loader worker runs with `globalOutbound: null`).
//
// Output is deterministic — regenerate with `pnpm vendor` and commit the result.

import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outDir = join(root, "src", "vendor");

// The four module-map specifiers. Every dependent is bundled with the OTHER
// three marked `external`, so at runtime they all resolve to the SINGLE
// vendored `preact` module in the map (shared hook state / options — critical
// for hooks + render-to-string to work against the same component instances).
const SPECIFIERS = [
  "preact",
  "preact/hooks",
  "preact/jsx-runtime",
  "preact-render-to-string",
];

// Each entry becomes one vendored ESM module string. `name` is the bare
// specifier the site code imports; `entry` is what esbuild bundles.
const ENTRIES = [
  { name: "preact", varName: "preact", entry: "preact" },
  { name: "preact/hooks", varName: "preactHooks", entry: "preact/hooks" },
  {
    name: "preact/jsx-runtime",
    varName: "preactJsxRuntime",
    entry: "preact/jsx-runtime",
  },
  {
    name: "preact-render-to-string",
    varName: "preactRenderToString",
    entry: "preact-render-to-string",
  },
];

async function bundleOne({ name }) {
  // Exact-match externals only. (esbuild's string `external` matches subpaths,
  // so "preact" would wrongly externalize "preact/hooks" — we need a plugin
  // that externalizes ONLY the exact other specifiers.)
  const externals = new Set(SPECIFIERS.filter((s) => s !== name));
  const exactExternalPlugin = {
    name: "exact-external",
    setup(pluginBuild) {
      pluginBuild.onResolve({ filter: /.*/ }, (args) => {
        if (externals.has(args.path)) {
          return { path: args.path, external: true };
        }
        return null;
      });
    },
  };
  const result = await build({
    stdin: {
      contents: `export * from ${JSON.stringify(name)};`,
      resolveDir: root,
      loader: "js",
    },
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    minify: true,
    legalComments: "none",
    plugins: [exactExternalPlugin],
    write: false,
  });
  return result.outputFiles[0].text;
}

async function main() {
  await mkdir(outDir, { recursive: true });
  for (const item of ENTRIES) {
    const code = await bundleOne(item);
    const banner =
      `// GENERATED by scripts/build-vendor.mjs — do not edit by hand.\n` +
      `// Self-contained ESM bundle of \`${item.name}\`, injected into the\n` +
      `// dynamic-site module map. Regenerate with \`pnpm vendor\`.\n`;
    const fileContents =
      banner + `export const ${item.varName}: string = ${JSON.stringify(code)};\n`;
    const fileName = item.varName.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());
    const outPath = join(outDir, `${fileName}.ts`);
    await writeFile(outPath, fileContents);
    console.log(`vendored ${item.name} -> ${outPath} (${code.length} bytes)`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
